### ISSUE TITLE
Streamer mode: Speed and radial coordinate could be shown safely

### ISSUE THREAD

**Issue by Soul-Burn** [Collective-SB/ISAN#43]
Streamer mode currently completely disables the ISAN display.

However data like speed could be safely shown even when in streamer mode.

Similarly, the radial axis, the one used to figure out in which zone we are is probably safe enough to be shown, as least at some lowered precision.

**Comment by Syb80** [comment]
Just change XX to :X, YY to :Y, ZZ to :Z and SS to :S (this is speed). If something goes wrong- you just did something wrong with the code: truncated it, pasted incorrectly etc. Please check twice the length of lines and/or redo the pasting from scratch. This applies to the V2 code which I’ve tested, although it is not in this repo afaik.

**Comment by Azurethi** [comment]
In 2.5 "streamer mode" has been renamed offline since it does completely shut down the system. It's intended to allow safe modifications to the code before restarting from line 1. An addon or new "streamer" bundle could have some potential, but seems like a small market. If you (or anyone else reading) does commonly stream, I'd be happy to work on a custom variant with you.
